using System.ComponentModel.DataAnnotations;

namespace AvicennaFeeAPI.Models
{
	public class uw_student
	{
		[Key]
		public int stuid { get; set; }
		public int? sid { get; set; }
		public string? sname { get; set; }
		public int? progid { get; set; }
		public string? asession { get; set; }
		public string? csession { get; set; }
		public string? section { get; set; }
		public bool? isactive { get; set; }
		public string? status { get; set; }
		public int? formid { get; set; }
		public string? ctype { get; set; }
		public bool? graduate { get; set; }
		public string? email { get; set; }
		public string? tel { get; set; }
		public string? mobile { get; set; }
		public DateTime? dob { get; set; }
		public string? cnic { get; set; }
		public int? age_y { get; set; }
		public string? nationality { get; set; }
		public string? religion { get; set; }
		public bool? hafiz { get; set; }
		public string? gender { get; set; }
		public string? fname { get; set; }
		public string? fcnic { get; set; }
		public string? fphone { get; set; }
		public string? fprof { get; set; }
		public string? forg { get; set; }
		public string? fdesig { get; set; }
		public double? fincome { get; set; }
		public string? ward_cat { get; set; }
		public int? ward_no { get; set; }
		public string? ward_desig { get; set; }
		public int? ward_scale { get; set; }
		public string? gname { get; set; }
		public string? gcnic { get; set; }
		public string? gtel { get; set; }
		public string? grelation { get; set; }
		public string? caddress { get; set; }
		public string? paddress { get; set; }
		public string? domicile { get; set; }
		public string? district { get; set; }
		public int? ssc_tmarks { get; set; }
		public int? ssc_omarks { get; set; }
		public double? ssc_percent { get; set; }
		public int? ssc_year { get; set; }
		public string? ssc_inst { get; set; }
		public string? ssc_maj { get; set; }
		public string? ssc_file { get; set; }
		public string? ssc_grade { get; set; }
		public string? hssc_status { get; set; }
		public int? hssc_tmarks { get; set; }
		public int? hssc_omarks { get; set; }
		public double? hssc_percent { get; set; }
		public int? hssc_year { get; set; }
		public string? hssc_inst { get; set; }
		public string? hssc_maj { get; set; }
		public string? hssc_file { get; set; }
		public string? hssc_grade { get; set; }
		public string? ug_status { get; set; }
		public int? ug_tmarks { get; set; }
		public int? ug_omarks { get; set; }
		public double? ug_percent { get; set; }
		public int? ug_year { get; set; }
		public string? ug_inst { get; set; }
		public string? ug_maj { get; set; }
		public string? ug_file { get; set; }
		public string? ug_grade { get; set; }
		public string? pg_status { get; set; }
		public int? pg_tmarks { get; set; }
		public int? pg_omarks { get; set; }
		public double? pg_percent { get; set; }
		public int? pg_year { get; set; }
		public string? pg_inst { get; set; }
		public string? pg_maj { get; set; }
		public string? pg_file { get; set; }
		public string? pg_grade { get; set; }
		public string? gat_file { get; set; }
		public string? chr_file { get; set; }
		public string? aff_file { get; set; }
		public string? noc_file { get; set; }
		public DateTime? lastmod { get; set; }
		public string? lastmodip { get; set; }
		public int? q_tmarks { get; set; }
		public int? q_omarks { get; set; }
		public double? q_percent { get; set; }
		public string? q_status { get; set; }
		public string? q_institute { get; set; }
		public int? q_year { get; set; }
		public string? et_type { get; set; }
		public int? et_tmarks { get; set; }
		public int? et_omarks { get; set; }
		public double? et_percent { get; set; }
		public string? meritlist { get; set; }
		public string? choice1 { get; set; }
		public string? choice2 { get; set; }
		public string? choice3 { get; set; }
		public string? choice4 { get; set; }
		public string? choice5 { get; set; }
		public double? marks_q { get; set; }
		public double? marks_test { get; set; }
		public double? marks_interview { get; set; }
		public double? marks_total { get; set; }
		public string? picture { get; set; }
		public string? remarks { get; set; }
		public DateTime? card_validity { get; set; }
		public string? card_session { get; set; }
		public string? bloodgrp { get; set; }
		public string? feecode { get; set; }
	}
}
